os: linux
language: python
python: "3.7"
dist: bionic
install:
# Install conan
  - pip install conan
# Automatic detection of your arch, compiler, etc.
  - conan user
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
script:
- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
- conan install -s compiler.libcxx=libstdc++11 .
- conan profile update settings.compiler.libcxx=libstdc++11 default
- conan profile update settings.compiler.version=7 default
- cmake .
- cmake --build . --config Release
- cmake --build . --target test
- cmake --build . --target package
- mkdir docs
- doxygen Doxyfile
deploy:
  - provider: pages
      skip_cleanup: true
      local_dir: $TRAVIS_BUILD_DIR/docs/html
      github_token: $GITHUB_TOKEN
      keep_history: true
      on:
        branch: master

  - provider: script
      skip_cleanup: true
      script:
      - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ufgund:$BINTRAY_API_KEY "https://api.bintray.com/content/fgund/OTUS_CPP/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=bionic;deb_component=main;deb_architecture=amd64;publish=1"
